// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Configuración Global → menu_items*
 */
export interface ConfiguracionGlobalDocumentDataMenuItemsItem {
  /**
   * texto field in *Configuración Global → menu_items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.menu_items[].texto
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto: prismic.KeyTextField;

  /**
   * enlace field in *Configuración Global → menu_items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.menu_items[].enlace
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enlace: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Configuración Global → redes_sociales*
 */
export interface ConfiguracionGlobalDocumentDataRedesSocialesItem {
  /**
   * plataforma field in *Configuración Global → redes_sociales*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.redes_sociales[].plataforma
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  plataforma: prismic.SelectField<
    "Facebook" | "Instagram" | "Twitter" | "Linkedin"
  >;

  /**
   * enlace field in *Configuración Global → redes_sociales*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.redes_sociales[].enlace
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enlace: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Configuración Global documents
 */
interface ConfiguracionGlobalDocumentData {
  /**
   * Tipo de Fondo field in *Configuración Global*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Color
   * - **API ID Path**: configuracion_global.tipo_fondo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tipo_fondo: prismic.SelectField<
    "Color" | "Imagen" | "Gradiente" | "nada",
    "filled"
  >;

  /**
   * Color de Fondo (hexadecimal) field in *Configuración Global*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #cebca5
   * - **API ID Path**: configuracion_global.color_fondo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  color_fondo: prismic.KeyTextField;

  /**
   * Imagen de Fondo field in *Configuración Global*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.imagen_fondo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen_fondo: prismic.ImageField<never>;

  /**
   * menu_items field in *Configuración Global*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_items: prismic.GroupField<
    Simplify<ConfiguracionGlobalDocumentDataMenuItemsItem>
  >;

  /**
   * footer_texto field in *Configuración Global*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.footer_texto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_texto: prismic.RichTextField;

  /**
   * redes_sociales field in *Configuración Global*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_global.redes_sociales[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  redes_sociales: prismic.GroupField<
    Simplify<ConfiguracionGlobalDocumentDataRedesSocialesItem>
  >;
}

/**
 * Configuración Global document from Prismic
 *
 * - **API ID**: `configuracion_global`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConfiguracionGlobalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ConfiguracionGlobalDocumentData>,
    "configuracion_global",
    Lang
  >;

/**
 * Item in *landing → Contacto del Footer*
 */
export interface LandingDocumentDataFooterContactoItem {
  /**
   * Teléfono field in *landing → Contacto del Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.footer_contacto[].telefono
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  telefono: prismic.KeyTextField;

  /**
   * Email field in *landing → Contacto del Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.footer_contacto[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Dirección field in *landing → Contacto del Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.footer_contacto[].direccion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  direccion: prismic.KeyTextField;
}

type LandingDocumentDataSlicesSlice =
  | ConfiguracionFondoSlice
  | VideoSectionSlice
  | SeccionInformativaSlice
  | GridCaracteristicasSlice
  | GridPartnersSlice
  | ProductoDestacadoSlice
  | SeccionContenidoSlice
  | HeroSlice;

/**
 * Content for landing documents
 */
interface LandingDocumentData {
  /**
   * logo field in *landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Contacto del Footer field in *landing*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.footer_contacto[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_contacto: prismic.GroupField<
    Simplify<LandingDocumentDataFooterContactoItem>
  >;

  /**
   * Slice Zone field in *landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice> /**
   * Meta Title field in *landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

/**
 * Content for texto documents
 */
interface TextoDocumentData {
  /**
   * contenido field in *texto*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contenido
   * - **API ID Path**: texto.contenido
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contenido: prismic.RichTextField;

  /**
   * tamano field in *texto*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: texto.Tamano
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  Tamano: prismic.SelectField<"pequeno" | "mediano" | "grande">;

  /**
   * alineacion field in *texto*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: texto.Alineacion
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  Alineacion: prismic.SelectField<"izquierda" | "centro" | "derecha">;
}

/**
 * texto document from Prismic
 *
 * - **API ID**: `texto`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TextoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TextoDocumentData>, "texto", Lang>;

export type AllDocumentTypes =
  | ConfiguracionGlobalDocument
  | LandingDocument
  | TextoDocument;

/**
 * Primary content in *Configuración de Fondo → Default → Primary*
 */
export interface ConfiguracionFondoSliceDefaultPrimary {
  /**
   * Tipo de Fondo field in *Configuración de Fondo → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Gradiente
   * - **API ID Path**: configuracion_fondo.default.primary.tipo_fondo
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tipo_fondo: prismic.SelectField<"Color" | "Imagen" | "Gradiente", "filled">;

  /**
   * Color de Fondo (hexadecimal) field in *Configuración de Fondo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #cebca5
   * - **API ID Path**: configuracion_fondo.default.primary.color_fondo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  color_fondo: prismic.KeyTextField;

  /**
   * Imagen de Fondo field in *Configuración de Fondo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: configuracion_fondo.default.primary.imagen_fondo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen_fondo: prismic.ImageField<never>;
}

/**
 * Default variation for Configuración de Fondo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConfiguracionFondoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConfiguracionFondoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Configuración de Fondo*
 */
type ConfiguracionFondoSliceVariation = ConfiguracionFondoSliceDefault;

/**
 * Configuración de Fondo Shared Slice
 *
 * - **API ID**: `configuracion_fondo`
 * - **Description**: Configuración del fondo de la página (color, imagen o gradiente)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConfiguracionFondoSlice = prismic.SharedSlice<
  "configuracion_fondo",
  ConfiguracionFondoSliceVariation
>;

/**
 * Item in *Sobre Nosotros → Default → Primary → Caracteristicas*
 */
export interface GridCaracteristicasSliceDefaultPrimaryCaracteristicasItem {
  /**
   * Título de la Característica field in *Sobre Nosotros → Default → Primary → Caracteristicas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_caracteristicas.default.primary.caracteristicas[].titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descripción de la Característica field in *Sobre Nosotros → Default → Primary → Caracteristicas*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_caracteristicas.default.primary.caracteristicas[].descripcion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  descripcion: prismic.RichTextField;

  /**
   * Icono field in *Sobre Nosotros → Default → Primary → Caracteristicas*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_caracteristicas.default.primary.caracteristicas[].icono
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icono: prismic.ImageField<never>;
}

/**
 * Primary content in *Sobre Nosotros → Default → Primary*
 */
export interface GridCaracteristicasSliceDefaultPrimary {
  /**
   * Título de la Sección field in *Sobre Nosotros → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_caracteristicas.default.primary.titulo_seccion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo_seccion: prismic.KeyTextField;

  /**
   * Subtitulo field in *Sobre Nosotros → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_caracteristicas.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Caracteristicas field in *Sobre Nosotros → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_caracteristicas.default.primary.caracteristicas[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  caracteristicas: prismic.GroupField<
    Simplify<GridCaracteristicasSliceDefaultPrimaryCaracteristicasItem>
  >;
}

/**
 * Default variation for Sobre Nosotros Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridCaracteristicasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridCaracteristicasSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Sobre Nosotros*
 */
type GridCaracteristicasSliceVariation = GridCaracteristicasSliceDefault;

/**
 * Sobre Nosotros Shared Slice
 *
 * - **API ID**: `grid_caracteristicas`
 * - **Description**: Grid con características, beneficios o información sobre la empresa
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridCaracteristicasSlice = prismic.SharedSlice<
  "grid_caracteristicas",
  GridCaracteristicasSliceVariation
>;

/**
 * Item in *Nuestros Partners → Default → Primary → Partners*
 */
export interface GridPartnersSliceDefaultPrimaryItemsItem {
  /**
   * Nombre del Partner field in *Nuestros Partners → Default → Primary → Partners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.items[].nombre
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nombre: prismic.KeyTextField;

  /**
   * Descripción field in *Nuestros Partners → Default → Primary → Partners*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.items[].descripcion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  descripcion: prismic.RichTextField;

  /**
   * Logo del Partner field in *Nuestros Partners → Default → Primary → Partners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.items[].imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Enlace del Partner field in *Nuestros Partners → Default → Primary → Partners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.items[].enlace
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enlace: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Nuestros Partners → Default → Primary*
 */
export interface GridPartnersSliceDefaultPrimary {
  /**
   * Título de la Sección field in *Nuestros Partners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.titulo_seccion
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo_seccion: prismic.KeyTextField;

  /**
   * Subtítulo field in *Nuestros Partners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Partners field in *Nuestros Partners → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_partners.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<GridPartnersSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Nuestros Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridPartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridPartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Nuestros Partners*
 */
type GridPartnersSliceVariation = GridPartnersSliceDefault;

/**
 * Nuestros Partners Shared Slice
 *
 * - **API ID**: `grid_partners`
 * - **Description**: Grid con logos y descripciones de partners o colaboradores
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridPartnersSlice = prismic.SharedSlice<
  "grid_partners",
  GridPartnersSliceVariation
>;

/**
 * Primary content in *Banner Principal → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Banner Principal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titulo
   * - **API ID Path**: hero.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtitulo field in *Banner Principal → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subtitulo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitulo: prismic.RichTextField;

  /**
   * Imagen de Fondo field in *Banner Principal → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.imagen_fondo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen_fondo: prismic.ImageField<never>;

  /**
   * Imagen Superior (arriba del título) field in *Banner Principal → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.imagen_superior
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen_superior: prismic.ImageField<never>;

  /**
   * Texto del Botón field in *Banner Principal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comenzar ahora
   * - **API ID Path**: hero.default.primary.texto_boton
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto_boton: prismic.KeyTextField;
}

/**
 * Default variation for Banner Principal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner Principal*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Banner Principal Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Banner principal de la página
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Bloque Secundario → Default → Primary*
 */
export interface ProductoDestacadoSliceDefaultPrimary {
  /**
   * Título field in *Bloque Secundario → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: producto_destacado.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descripción field in *Bloque Secundario → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: producto_destacado.default.primary.descripcion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  descripcion: prismic.RichTextField;

  /**
   * Imagen del Producto field in *Bloque Secundario → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: producto_destacado.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Texto del Botón field in *Bloque Secundario → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ver más detalles
   * - **API ID Path**: producto_destacado.default.primary.texto_boton
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto_boton: prismic.KeyTextField;

  /**
   * Enlace del Botón field in *Bloque Secundario → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: producto_destacado.default.primary.enlace_boton
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enlace_boton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Posición de la Imagen field in *Bloque Secundario → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Izquierda
   * - **API ID Path**: producto_destacado.default.primary.posicion_imagen
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  posicion_imagen: prismic.SelectField<"Izquierda" | "Derecha", "filled">;
}

/**
 * Default variation for Bloque Secundario Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductoDestacadoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductoDestacadoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bloque Secundario*
 */
type ProductoDestacadoSliceVariation = ProductoDestacadoSliceDefault;

/**
 * Bloque Secundario Shared Slice
 *
 * - **API ID**: `producto_destacado`
 * - **Description**: Producto o servicio principal
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductoDestacadoSlice = prismic.SharedSlice<
  "producto_destacado",
  ProductoDestacadoSliceVariation
>;

/**
 * Primary content in *Bloque Principal → Default → Primary*
 */
export interface SeccionContenidoSliceDefaultPrimary {
  /**
   * Título field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.contenido
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contenido: prismic.RichTextField;

  /**
   * Imagen field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Posición de la Imagen field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: izquierda
   * - **API ID Path**: seccion_contenido.default.primary.posicion_imagen
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  posicion_imagen: prismic.SelectField<"izquierda" | "derecha", "filled">;

  /**
   * Texto del Botón field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.texto_boton
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto_boton: prismic.KeyTextField;

  /**
   * Enlace del Botón field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.enlace_boton
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enlace_boton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Bloque Principal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeccionContenidoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeccionContenidoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bloque Principal*
 */
type SeccionContenidoSliceVariation = SeccionContenidoSliceDefault;

/**
 * Bloque Principal Shared Slice
 *
 * - **API ID**: `seccion_contenido`
 * - **Description**: Sección con imagen y texto
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeccionContenidoSlice = prismic.SharedSlice<
  "seccion_contenido",
  SeccionContenidoSliceVariation
>;

/**
 * Primary content in *Bloque Principal → Default → Primary*
 */
export interface SeccionContenidoSliceDefaultPrimary {
  /**
   * Título field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.contenido
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contenido: prismic.RichTextField;

  /**
   * Imagen field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Posición de la Imagen field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: izquierda
   * - **API ID Path**: seccion_contenido.default.primary.posicion_imagen
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  posicion_imagen: prismic.SelectField<"izquierda" | "derecha", "filled">;

  /**
   * Texto del Botón field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.texto_boton
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  texto_boton: prismic.KeyTextField;

  /**
   * Enlace del Botón field in *Bloque Principal → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_contenido.default.primary.enlace_boton
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  enlace_boton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Bloque Principal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeccionContenidoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeccionContenidoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bloque Principal*
 */
type SeccionContenidoSliceVariation = SeccionContenidoSliceDefault;

/**
 * Bloque Principal Shared Slice
 *
 * - **API ID**: `seccion_contenido`
 * - **Description**: Sección con imagen y texto
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeccionContenidoSlice = prismic.SharedSlice<
  "seccion_contenido",
  SeccionContenidoSliceVariation
>;

/**
 * Primary content in *Información de Contacto → Default → Primary*
 */
export interface SeccionInformativaSliceDefaultPrimary {
  /**
   * Título field in *Información de Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_informativa.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  titulo: prismic.KeyTextField;

  /**
   * Contenido field in *Información de Contacto → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_informativa.default.primary.contenido
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contenido: prismic.RichTextField;

  /**
   * Imagen field in *Información de Contacto → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: seccion_informativa.default.primary.imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Posición de la Imagen field in *Información de Contacto → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Izquierda
   * - **API ID Path**: seccion_informativa.default.primary.posicion_imagen
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  posicion_imagen: prismic.SelectField<"Izquierda" | "Derecha", "filled">;
}

/**
 * Default variation for Información de Contacto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeccionInformativaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SeccionInformativaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Información de Contacto*
 */
type SeccionInformativaSliceVariation = SeccionInformativaSliceDefault;

/**
 * Información de Contacto Shared Slice
 *
 * - **API ID**: `seccion_informativa`
 * - **Description**: Sección informativa con contenido y opción de botón de contacto
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SeccionInformativaSlice = prismic.SharedSlice<
  "seccion_informativa",
  SeccionInformativaSliceVariation
>;

/**
 * Primary content in *Video Promocional → Default → Primary*
 */
export interface VideoSectionSliceDefaultPrimary {
  /**
   * URL de video field in *Video Promocional → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_section.default.primary.url_video
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url_video: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Video Promocional Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video Promocional*
 */
type VideoSectionSliceVariation = VideoSectionSliceDefault;

/**
 * Video Promocional Shared Slice
 *
 * - **API ID**: `video_section`
 * - **Description**: Video de YouTube o Vimeo que se reproduce automáticamente
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSectionSlice = prismic.SharedSlice<
  "video_section",
  VideoSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ConfiguracionGlobalDocument,
      ConfiguracionGlobalDocumentData,
      ConfiguracionGlobalDocumentDataMenuItemsItem,
      ConfiguracionGlobalDocumentDataRedesSocialesItem,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataFooterContactoItem,
      LandingDocumentDataSlicesSlice,
      TextoDocument,
      TextoDocumentData,
      AllDocumentTypes,
      ConfiguracionFondoSlice,
      ConfiguracionFondoSliceDefaultPrimary,
      ConfiguracionFondoSliceVariation,
      ConfiguracionFondoSliceDefault,
      GridCaracteristicasSlice,
      GridCaracteristicasSliceDefaultPrimaryCaracteristicasItem,
      GridCaracteristicasSliceDefaultPrimary,
      GridCaracteristicasSliceVariation,
      GridCaracteristicasSliceDefault,
      GridPartnersSlice,
      GridPartnersSliceDefaultPrimaryItemsItem,
      GridPartnersSliceDefaultPrimary,
      GridPartnersSliceVariation,
      GridPartnersSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ProductoDestacadoSlice,
      ProductoDestacadoSliceDefaultPrimary,
      ProductoDestacadoSliceVariation,
      ProductoDestacadoSliceDefault,
      SeccionContenidoSlice,
      SeccionContenidoSliceDefaultPrimary,
      SeccionContenidoSliceVariation,
      SeccionContenidoSliceDefault,
      SeccionContenidoSlice,
      SeccionContenidoSliceDefaultPrimary,
      SeccionContenidoSliceVariation,
      SeccionContenidoSliceDefault,
      SeccionInformativaSlice,
      SeccionInformativaSliceDefaultPrimary,
      SeccionInformativaSliceVariation,
      SeccionInformativaSliceDefault,
      VideoSectionSlice,
      VideoSectionSliceDefaultPrimary,
      VideoSectionSliceVariation,
      VideoSectionSliceDefault,
    };
  }
}
